"""
Curated drug-drug interaction reference data.

WHY THIS IS A HAND-WRITTEN LIST, NOT AN AI CALL OR A SCRAPED DATABASE:
Same reasoning as app/rules/engine.py's severity floor - an LLM asked
"do these two drugs interact?" can sound confident while being wrong,
and getting this specific kind of question wrong (missing a real
dangerous interaction, or inventing one that doesn't exist) is a
serious harm, not a UX annoyance. Every entry below is a well-
established, textbook-level pharmacological interaction (the kind
covered in standard pharmacology references and taught in clinical
training) - not a novel or borderline claim requiring a specific
citation. Nothing here was generated by an AI model.

SCOPE - read before assuming this is comprehensive:
This is a SMALL, DELIBERATELY LIMITED list (~35 entries) covering some
of the most well-known and clinically significant interactions across
common drug classes (anticoagulants, SSRIs/MAOIs, cardiac drugs,
diuretics, NSAIDs, certain antibiotics/antifungals, one herbal
supplement). It is NOT exhaustive - real drug interaction databases
like DDInter cover 300,000+ interaction pairs. A drug combination not
appearing here does NOT mean it's safe - it may mean the interaction
simply isn't in this small reference set yet. See PROJECT_STATE.md for
the researched path to a much larger dataset (DDInter, CC BY-NC-SA
4.0 - same non-commercial licensing question already flagged for the
WHO RAG sources) if broader coverage is wanted later.

Matching is done by exact, case-insensitive name/alias lookup (see
app/interactions/matcher.py) - no fuzzy matching, no AI-assisted name
resolution. A misspelled or unlisted drug name simply won't match,
and the response says so explicitly rather than silently skipping it.
"""

from dataclasses import dataclass, field
from enum import Enum


class InteractionSeverity(str, Enum):
    """
    Deliberately just two levels, not four (unlike Severity for symptom
    triage) - every entry in this list was chosen specifically because
    it's clinically significant. There's no "LOW" interaction entry
    here; if it's not worth listing, it's not in this file at all.
    """

    MODERATE = "MODERATE"
    MAJOR = "MAJOR"


@dataclass(frozen=True)
class DrugEntry:
    """A drug and the names a person might reasonably type for it."""

    canonical_name: str
    aliases: tuple[str, ...] = field(default_factory=tuple)

    def all_names(self) -> tuple[str, ...]:
        return (self.canonical_name,) + self.aliases


@dataclass(frozen=True)
class InteractionEntry:
    drug_a: DrugEntry
    drug_b: DrugEntry
    severity: InteractionSeverity
    description: str  # plain-language explanation of the risk


INTERACTIONS: tuple[InteractionEntry, ...] = (
    InteractionEntry(
        DrugEntry("warfarin", ("coumadin",)),
        DrugEntry("ibuprofen", ("advil", "motrin", "nsaids", "naproxen", "aleve")),
        InteractionSeverity.MAJOR,
        "Increased bleeding risk - NSAIDs impair platelet function on top of warfarin's anticoagulant effect.",
    ),
    InteractionEntry(
        DrugEntry("warfarin", ("coumadin",)),
        DrugEntry("aspirin", ("acetylsalicylic acid",)),
        InteractionSeverity.MAJOR,
        "Significantly increased bleeding risk when combined - both affect clotting through different mechanisms.",
    ),
    InteractionEntry(
        DrugEntry("warfarin", ("coumadin",)),
        DrugEntry("amiodarone", ("cordarone",)),
        InteractionSeverity.MAJOR,
        "Amiodarone can raise warfarin blood levels substantially, increasing bleeding risk - often needs a warfarin dose reduction.",
    ),
    InteractionEntry(
        DrugEntry("warfarin", ("coumadin",)),
        DrugEntry("fluconazole", ("diflucan",)),
        InteractionSeverity.MAJOR,
        "Fluconazole can markedly increase warfarin levels, raising bleeding risk.",
    ),
    InteractionEntry(
        DrugEntry("warfarin", ("coumadin",)),
        DrugEntry("ciprofloxacin", ("cipro",)),
        InteractionSeverity.MODERATE,
        "Can increase warfarin's blood-thinning effect and bleeding risk.",
    ),
    InteractionEntry(
        DrugEntry("warfarin", ("coumadin",)),
        DrugEntry("metronidazole", ("flagyl",)),
        InteractionSeverity.MAJOR,
        "Can significantly increase warfarin levels and bleeding risk.",
    ),
    InteractionEntry(
        DrugEntry("maois", ("phenelzine", "tranylcypromine", "isocarboxazid")),
        DrugEntry("ssris", ("fluoxetine", "sertraline", "paroxetine", "citalopram", "escitalopram")),
        InteractionSeverity.MAJOR,
        "Risk of serotonin syndrome (a potentially life-threatening reaction) - these should not be combined.",
    ),
    InteractionEntry(
        DrugEntry("maois", ("phenelzine", "tranylcypromine", "isocarboxazid")),
        DrugEntry("tramadol", ("ultram",)),
        InteractionSeverity.MAJOR,
        "Risk of serotonin syndrome and lowered seizure threshold.",
    ),
    InteractionEntry(
        DrugEntry("ssris", ("fluoxetine", "sertraline", "paroxetine", "citalopram", "escitalopram")),
        DrugEntry("tramadol", ("ultram",)),
        InteractionSeverity.MODERATE,
        "Risk of serotonin syndrome when combined.",
    ),
    InteractionEntry(
        DrugEntry("ssris", ("fluoxetine", "sertraline", "paroxetine", "citalopram", "escitalopram")),
        DrugEntry("triptans", ("sumatriptan", "rizatriptan", "zolmitriptan")),
        InteractionSeverity.MODERATE,
        "Combined use carries a risk of serotonin syndrome.",
    ),
    InteractionEntry(
        DrugEntry("ssris", ("fluoxetine", "sertraline", "paroxetine", "citalopram", "escitalopram")),
        DrugEntry("ibuprofen", ("advil", "motrin", "nsaids", "naproxen", "aleve")),
        InteractionSeverity.MODERATE,
        "Increased risk of gastrointestinal bleeding when combined.",
    ),
    InteractionEntry(
        DrugEntry("st john's wort", ("hypericum", "st johns wort")),
        DrugEntry("ssris", ("fluoxetine", "sertraline", "paroxetine", "citalopram", "escitalopram")),
        InteractionSeverity.MAJOR,
        "Risk of serotonin syndrome - this herbal supplement has its own serotonergic activity.",
    ),
    InteractionEntry(
        DrugEntry("st john's wort", ("hypericum", "st johns wort")),
        DrugEntry("oral contraceptives", ("birth control pills", "the pill")),
        InteractionSeverity.MAJOR,
        "Can significantly reduce contraceptive effectiveness by speeding up hormone metabolism.",
    ),
    InteractionEntry(
        DrugEntry("lisinopril", ("ace inhibitors", "enalapril", "ramipril")),
        DrugEntry("spironolactone", ("aldactone", "potassium-sparing diuretics")),
        InteractionSeverity.MAJOR,
        "Risk of dangerously high potassium levels (hyperkalemia) when combined.",
    ),
    InteractionEntry(
        DrugEntry("lisinopril", ("ace inhibitors", "enalapril", "ramipril")),
        DrugEntry("losartan", ("arbs", "valsartan", "irbesartan")),
        InteractionSeverity.MODERATE,
        "Combining ACE inhibitors and ARBs raises risk of high potassium and reduced kidney function without added benefit.",
    ),
    InteractionEntry(
        DrugEntry("lisinopril", ("ace inhibitors", "enalapril", "ramipril")),
        DrugEntry("ibuprofen", ("advil", "motrin", "nsaids", "naproxen", "aleve")),
        InteractionSeverity.MODERATE,
        "NSAIDs can reduce the blood-pressure-lowering effect and impair kidney function, especially with diuretics too.",
    ),
    InteractionEntry(
        DrugEntry("simvastatin", ("statins", "atorvastatin", "lovastatin")),
        DrugEntry("gemfibrozil", ("fibrates",)),
        InteractionSeverity.MAJOR,
        "Significantly increased risk of severe muscle breakdown (rhabdomyolysis).",
    ),
    InteractionEntry(
        DrugEntry("simvastatin", ("statins", "atorvastatin", "lovastatin")),
        DrugEntry("clarithromycin", ("macrolide antibiotics", "erythromycin")),
        InteractionSeverity.MAJOR,
        "These antibiotics can raise statin levels substantially, increasing rhabdomyolysis risk.",
    ),
    InteractionEntry(
        DrugEntry("digoxin", ("lanoxin",)),
        DrugEntry("furosemide", ("lasix", "diuretics", "hydrochlorothiazide")),
        InteractionSeverity.MODERATE,
        "Diuretic-induced low potassium can increase digoxin toxicity risk.",
    ),
    InteractionEntry(
        DrugEntry("digoxin", ("lanoxin",)),
        DrugEntry("amiodarone", ("cordarone",)),
        InteractionSeverity.MAJOR,
        "Amiodarone can raise digoxin levels substantially - often needs a digoxin dose reduction.",
    ),
    InteractionEntry(
        DrugEntry("methotrexate", ()),
        DrugEntry("ibuprofen", ("advil", "motrin", "nsaids", "naproxen", "aleve")),
        InteractionSeverity.MAJOR,
        "NSAIDs can reduce methotrexate clearance, increasing risk of serious toxicity.",
    ),
    InteractionEntry(
        DrugEntry("methotrexate", ()),
        DrugEntry("trimethoprim-sulfamethoxazole", ("bactrim", "co-trimoxazole")),
        InteractionSeverity.MAJOR,
        "Combined use raises risk of serious bone marrow suppression.",
    ),
    InteractionEntry(
        DrugEntry("lithium", ()),
        DrugEntry("ibuprofen", ("advil", "motrin", "nsaids", "naproxen", "aleve")),
        InteractionSeverity.MODERATE,
        "NSAIDs can raise lithium levels, increasing toxicity risk.",
    ),
    InteractionEntry(
        DrugEntry("lithium", ()),
        DrugEntry("lisinopril", ("ace inhibitors", "enalapril", "ramipril")),
        InteractionSeverity.MODERATE,
        "ACE inhibitors can raise lithium levels, increasing toxicity risk.",
    ),
    InteractionEntry(
        DrugEntry("lithium", ()),
        DrugEntry("hydrochlorothiazide", ("thiazide diuretics",)),
        InteractionSeverity.MODERATE,
        "Thiazide diuretics can raise lithium levels, increasing toxicity risk.",
    ),
    InteractionEntry(
        DrugEntry("clopidogrel", ("plavix",)),
        DrugEntry("omeprazole", ("proton pump inhibitors", "ppis", "esomeprazole")),
        InteractionSeverity.MODERATE,
        "Some PPIs may reduce clopidogrel's antiplatelet effectiveness.",
    ),
    InteractionEntry(
        DrugEntry("alprazolam", ("benzodiazepines", "diazepam", "lorazepam", "xanax")),
        DrugEntry("oxycodone", ("opioids", "hydrocodone", "morphine", "codeine")),
        InteractionSeverity.MAJOR,
        "Combined use significantly increases risk of severe respiratory depression and can be fatal.",
    ),
    InteractionEntry(
        DrugEntry("alprazolam", ("benzodiazepines", "diazepam", "lorazepam", "xanax")),
        DrugEntry("alcohol", ()),
        InteractionSeverity.MAJOR,
        "Both are CNS depressants - combined use significantly increases sedation and respiratory depression risk.",
    ),
    InteractionEntry(
        DrugEntry("oxycodone", ("opioids", "hydrocodone", "morphine", "codeine")),
        DrugEntry("alcohol", ()),
        InteractionSeverity.MAJOR,
        "Combined use significantly increases risk of severe respiratory depression and can be fatal.",
    ),
    InteractionEntry(
        DrugEntry("metoprolol", ("beta-blockers", "atenolol", "propranolol")),
        DrugEntry("verapamil", ("diltiazem", "non-dihydropyridine calcium channel blockers")),
        InteractionSeverity.MAJOR,
        "Combined use can cause severe bradycardia (slow heart rate) and heart block.",
    ),
    InteractionEntry(
        DrugEntry("sildenafil", ("viagra", "tadalafil", "cialis", "vardenafil")),
        DrugEntry("nitroglycerin", ("nitrates", "isosorbide")),
        InteractionSeverity.MAJOR,
        "Combined use can cause a severe, potentially life-threatening drop in blood pressure. Must not be combined.",
    ),
    InteractionEntry(
        DrugEntry("theophylline", ()),
        DrugEntry("ciprofloxacin", ("cipro",)),
        InteractionSeverity.MODERATE,
        "Ciprofloxacin can raise theophylline levels, increasing toxicity risk (nausea, tremor, seizures).",
    ),
    InteractionEntry(
        DrugEntry("carbamazepine", ("tegretol",)),
        DrugEntry("oral contraceptives", ("birth control pills", "the pill")),
        InteractionSeverity.MAJOR,
        "Carbamazepine speeds up hormone metabolism and can significantly reduce contraceptive effectiveness.",
    ),
    InteractionEntry(
        DrugEntry("insulin", ("sulfonylureas", "glipizide", "glyburide")),
        DrugEntry("metoprolol", ("beta-blockers", "atenolol", "propranolol")),
        InteractionSeverity.MODERATE,
        "Beta-blockers can mask the warning symptoms (like a fast heartbeat) of low blood sugar.",
    ),
    InteractionEntry(
        DrugEntry("metformin", ()),
        DrugEntry("iodinated contrast dye", ("contrast dye", "iv contrast")),
        InteractionSeverity.MODERATE,
        "Rare but serious risk of lactic acidosis, particularly with reduced kidney function - metformin is often paused around contrast imaging.",
    ),
)
