export const ROUTES = {
  SPLASH: "/",
  LOGIN: "/login",
  SIGNUP: "/signup",
  DASHBOARD: "/dashboard",
  SYMPTOM_ANALYSIS: "/analysis",
  ANALYSIS_RESULT: "/analysis/result",
  PASSPORT: "/passport",
  HISTORY: "/history",
  REMINDERS: "/reminders",
  DRUG_INTERACTIONS: "/drug-interactions",
  CAREGIVERS: "/caregivers",
  CAREGIVER_PATIENT: "/caregivers/patient/:patientId",
  ADMIN_ANALYTICS: "/admin/analytics",
  SOS: "/sos",
};
